version: '3.4'
services:

  erp_ws-chat:
    build: ./
    networks:
      - site
    ports:
      - "8069:80"
    restart: always

networks:
  site:
    name: docker_site
#docker network create --gateway 10.9.0.1 --subnet 10.9.0.0/24 go
