version: '3.4'
services:

  micro-services-chat:
    build: ./
    container_name: micro-services-chat
    image: micseres/micro-services-chat
    networks:
      erp:
        ipv4_address: 10.7.0.169
      go:
        ipv4_address: 10.9.0.169
    ports:
      - "8069:80"
    volumes:
      - ./:/app
    restart: always

networks:
  go:
    external: true
  erp:
    external: true
#docker network create --gateway 10.9.0.1 --subnet 10.9.0.0/24 go